name: MLflow CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install MLflow
      run: |
        pip install mlflow==2.19.0 scikit-learn pandas

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        miniforge-variant: Mambaforge
        python-version: 3.12.7
        auto-update-conda: true

    - name: Create env via mamba
      run: |
        mamba env create -f MLProject/conda.yaml

    - name: Run MLflow Project
      run: |
        source $CONDA/etc/profile.d/conda.sh
        mlflow run MLProject

    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: mlruns

    - name: Build Docker Image
      run: |
        RUN_ID=$(ls -td mlruns/*/* | head -1 | cut -d'/' -f3)
        mlflow models build-docker -m "runs:/$RUN_ID/model" -n red-wine-model

    - name: Login Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
        -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker Image
      run: |
        docker tag "${{ secrets.DOCKER_USERNAME }}/wine-quality-app:latest" "${{ secrets.DOCKER_USERNAME }}/wine-quality-app:v1"

    - name: Push Docker Image
      run: |
        docker push "${{ secrets.DOCKER_USERNAME }}/wine-quality-app:latest"
        docker push "${{ secrets.DOCKER_USERNAME }}/wine-quality-app:v1"