name: MLflow CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install MLflow
      run: |
        pip install mlflow==2.19.0 scikit-learn pandas

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.12.7
        auto-update-conda: true

    - name: Create env via mamba
      run: |
        mamba env create -f MLProject/conda.yaml || true

    - name: Run MLflow Project
      run: |
        source /usr/share/miniconda3/etc/profile.d/conda.sh
        mlflow run MLProject
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: mlruns
    - name: Build Docker Image
      run: |
        mlflow models build-docker \
          -m "runs:/$(ls mlruns/*/*/artifacts/model)" \
          -n red-wine-model

    - name: Login Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
        -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker tag red-wine-model ${{ secrets.DOCKER_USERNAME }}/red-wine-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/red-wine-model:latest
